env:
  es6: true
  node: true
  jest: true
  jasmine: true
  browser: true
extends:
  - '@trustedshops/eslint-config-etrusted-aaa-react'
globals:
  DocumentEventMap: readonly
  CustomEventInit: readonly
  GlobalEventHandlersEventMap: readonly
  globalThis: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  react:
    pragma: h
    version: latest
plugins:
  - '@typescript-eslint'
  - react
rules:
  'import/no-named-default': 0
